<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEkKlGrV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEkKlGrV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEkKlGrV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEkKlGrV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEkKlGrV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EkKlGrV',
    'container.build_id' => 'c2eb25c5',
    'container.build_time' => 1632411154,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEkKlGrV');
