<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZNL4rQ2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNL4rQ2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZNL4rQ2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZNL4rQ2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZNL4rQ2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZNL4rQ2',
    'container.build_id' => 'fee7c5f8',
    'container.build_time' => 1631867429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNL4rQ2');
